### ISSUE TITLE
BoincTUI for FAH

### ISSUE THREAD

**Issue by ProDigit** [mpentler/boinctui-extended#9]
No issue, but feat request.
Please consider supporting FAH,
We need a similar program for Folding at Home.
For several years now the FahControl (like Boinc Manager, but for FAH), is no longer compatible with anything over 18.10. FAH doesn't seem to have any resources to fix it, so there's no manager.

I wished something like BoincTUI could exist for FAH, and wondered if some of the parameters could be copied from FAHControl to BoincTUI, and converted in something like FAHTUI?

I have no expertise in this.

**Comment by mpentler** [comment]
Hello! Thank you for taking an interest. I’m not sure what would be required to add support for this. There’s no BOINC support on FAH at all then?

I mean, presumably it’d be a case of adding code to poll a FAH client running elsewhere. Which would need that FAH client to expose its status somehow in return. Is there any kind of API available?

It would absolutely be beyond my skills I’m afraid - I’m just maintaining this, merging patches, and getting help from friends for coding issues and tidying up bugs in the original codebase.

**Comment by ProDigit** [comment]
FAH (Folding At Home) and Boinc once used the same platform, but they separated ways, as FAH needed certain proprietary code that could not be implemented in Boinc, but was necessary to do the work FAH does. It's partly closed source (only the core code pertaining to FAH).
FAHControl should be open source.
The operation of the two, function pretty much the same. 
FahClient runs much like Boinc Client, with the exception that starting it with '/etc/init.d/fahclient start', newer versions favoring systemd. FahControl is pretty much a derivative of Boinc MGR, modified a bit, and perhaps more fah optimized.
It only accepts 1 project (FAH), has a download/upload and task window.

I think the main need, is for running a terminal manager from a local client. 
Remotely, there's always SSH.

**Comment by rustyshackleford36** [comment]
I’m not a programmer by any means but I am willing to do some research and see if it’s remotely viable. Maybe be able to rope some people in from either community.

**Comment by mpentler** [comment]
If FAHControl’s source is available that’s gotta be possible surely? Change some data structures and the authentication methods and whatnot?

**Comment by mpentler** [comment]
PS: Long-term I want somebody who still uses BOINC to takeover maintaining this project, so somebody else may want to add the features requested...

Hit me up, folks!

**Comment by mpentler** [comment]
Realistically I think I have to close this as I’m definitely not adding any functionality myself any time soon. If anyone wants to pick it up I’ll take a PR, but hopefully by that point I’ll have handed this fork on to someone else for maintaining.
